@extends('layouts/contentNavbarLayout')

@section('title', 'AI Generated Posters')

@section('content')
<div class="admin-page">

    <div class="admin-page-header d-flex justify-content-between align-items-center mb-4">
        <div class="admin-page-header__left">
            <h4 class="admin-page-header__title">AI Generated Posters</h4>
            <p class="admin-page-header__subtitle">Review, approve, and manage social media marketing posters generated by users using Google Gemini.</p>
        </div>
    </div>

    @component('admin.components.datatable', [
        'title'     => 'Generated Posters',
        'subtitle'  => 'Review pending design outputs.',
        'paginator' => $posters,
        'createUrl' => null,
        'search'    => $search,
        'perPage'   => $perPage,
        'sort'      => 'created_at',
        'direction' => 'desc',
        'columns'   => [
            ['label' => '#',          'field' => 'id',         'sortable' => false],
            ['label' => 'Generated Image', 'sortable' => false],
            ['label' => 'User',       'sortable' => false],
            ['label' => 'Business',   'sortable' => false],
            ['label' => 'Prompt',     'sortable' => false],
            ['label' => 'Status',     'field' => 'status',     'sortable' => false],
            ['label' => 'Created Date', 'field' => 'created_at', 'sortable' => false],
            ['label' => 'Actions',    'actions' => true],
        ],
    ])
        @forelse($posters as $item)
            <tr>
                <td class="cell-muted">{{ $item->id }}</td>
                <td>
                    @if($item->generated_image)
                        <img src="{{ $item->generated_image }}" alt="Generated Banner" class="rounded" style="width: 50px; height: 50px; object-fit: cover; border: 1px solid #cbd5e1;">
                    @else
                        <span class="text-muted">No Image</span>
                    @endif
                </td>
                <td>
                    <div class="cell-primary fw-medium">{{ $item->user->name ?? '—' }}</div>
                    <div class="cell-muted small">{{ $item->user->email ?? '' }}</div>
                </td>
                <td>
                    <div class="cell-primary fw-medium">{{ $item->business->name ?? ($item->user->club_name ?? '—') }}</div>
                </td>
                <td style="max-width: 200px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap;">
                    <span title="{{ $item->prompt }}">{{ $item->prompt }}</span>
                </td>
                <td>
                    @php
                        $statusBadge = match($item->status) {
                            'approved' => 'bg-label-success',
                            'rejected' => 'bg-label-danger',
                            default    => 'bg-label-warning',
                        };
                    @endphp
                    <span class="badge {{ $statusBadge }} text-capitalize">
                        {{ $item->status }}
                    </span>
                </td>
                <td class="cell-muted">{{ $item->created_at?->format('Y-m-d') }}</td>
                <td class="text-end">
                    <div class="d-inline-flex align-items-center gap-1">
                        @include('admin.components.action-buttons', [
                            'type'  => 'view',
                            'href'  => route('admin.ai-generated-posters.show', $item),
                            'title' => 'View Details',
                        ])

                        @if($item->status === 'pending')
                            <form action="{{ route('admin.ai-generated-posters.approve', $item) }}" method="POST" class="d-inline">
                                @csrf
                                <button type="submit" class="action-icon-btn action-icon-edit border-0 bg-transparent text-success" title="Approve Poster">
                                    <i class="mdi mdi-check-circle-outline"></i>
                                </button>
                            </form>

                            <button type="button" class="action-icon-btn action-icon-delete border-0 bg-transparent text-danger" title="Reject Poster" data-bs-toggle="modal" data-bs-target="#rejectModal-{{ $item->id }}">
                                <i class="mdi mdi-close-circle-outline"></i>
                            </button>

                            {{-- Rejection Modal --}}
                            <div class="modal fade" id="rejectModal-{{ $item->id }}" tabindex="-1" aria-labelledby="rejectModalLabel-{{ $item->id }}" aria-hidden="true">
                                <div class="modal-dialog text-start">
                                    <div class="modal-content">
                                        <form action="{{ route('admin.ai-generated-posters.reject', $item) }}" method="POST">
                                            @csrf
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="rejectModalLabel-{{ $item->id }}">Reject AI Poster #{{ $item->id }}</h5>
                                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                            </div>
                                            <div class="modal-body">
                                                <div class="mb-3">
                                                    <label class="form-label fw-semibold">Rejection Reason</label>
                                                    <textarea name="rejection_reason" class="form-control" rows="3" placeholder="Explain why this poster was rejected (branding issues, wrong prompt alignment, etc.)..." required></textarea>
                                                </div>
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Cancel</button>
                                                <button type="submit" class="btn btn-danger">Submit Rejection</button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        @endif
                    </div>
                </td>
            </tr>
        @empty
            <tr>
                <td colspan="8" class="admin-empty-state">No AI generated posters found.</td>
            </tr>
        @endforelse
    @endcomponent

</div>
@endsection
